//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ai_image_generation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub story_title: String,
    pub node_summary: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub node_content: Option<String>,
    pub style: String,
    pub resolution: String,
    pub image_url: String,
    pub temp_url: Option<String>,
    pub temp_url_expires_at: Option<TimeDateTimeWithTimeZone>,
    pub width: i32,
    pub height: i32,
    pub file_size_bytes: Option<i32>,
    pub credits_used: i32,
    pub generation_time_ms: Option<i32>,
    pub ai_provider: Option<String>,
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    pub created_at: TimeDateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
