//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "credit_purchases")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub original_transaction_id: Option<String>,
    #[sea_orm(unique)]
    pub transaction_id: String,
    pub product_id: String,
    pub platform: String,
    pub amount: i32,
    pub consumed: i32,
    pub purchase_date: TimeDateTimeWithTimeZone,
    pub verified_at: TimeDateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub receipt_data: Option<String>,
    pub revoked_at: Option<TimeDateTimeWithTimeZone>,
    pub revoked_reason: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
