//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "iap_receipt_cache")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: uuid::Uuid,
    #[sea_orm(unique)]
    pub purchase_identity: String,
    pub platform: String,
    pub purchase_tier: String,
    pub product_id: Option<String>,
    pub receipt_hash: Option<String>,
    pub valid_until: Option<time::OffsetDateTime>,
    pub last_verified_at: time::OffsetDateTime,
    pub created_at: time::OffsetDateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
