//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use super::sea_orm_active_enums::AccountTier;
use super::sea_orm_active_enums::UserStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub email: Option<String>,
    pub email_verified: bool,
    pub full_name: Option<String>,
    pub status: UserStatus,
    pub account_tier: AccountTier,
    pub created_at: TimeDateTimeWithTimeZone,
    pub updated_at: TimeDateTimeWithTimeZone,
    pub last_login_at: Option<TimeDateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::credit_purchases::Entity")]
    CreditPurchases,
    #[sea_orm(has_many = "super::iap_receipt_cache::Entity")]
    IapReceiptCache,
    #[sea_orm(has_many = "super::quota_usage::Entity")]
    QuotaUsage,
    #[sea_orm(has_many = "super::refresh_tokens::Entity")]
    RefreshTokens,
    #[sea_orm(has_many = "super::user_auth_methods::Entity")]
    UserAuthMethods,
    #[sea_orm(has_one = "super::user_credit_balance::Entity")]
    UserCreditBalance,
    #[sea_orm(has_one = "super::welcome_bonuses::Entity")]
    WelcomeBonuses,
}

impl Related<super::credit_purchases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CreditPurchases.def()
    }
}

impl Related<super::iap_receipt_cache::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IapReceiptCache.def()
    }
}

impl Related<super::quota_usage::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QuotaUsage.def()
    }
}

impl Related<super::refresh_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RefreshTokens.def()
    }
}

impl Related<super::user_auth_methods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserAuthMethods.def()
    }
}

impl Related<super::user_credit_balance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserCreditBalance.def()
    }
}

impl Related<super::welcome_bonuses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WelcomeBonuses.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
